# Generated by Django 4.2.2 on 2023-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donate_remove_user_plan_delete_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='email',
        ),
        migrations.AddField(
            model_name='donate',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
